### ISSUE TITLE
Error in hexvalue - from hexagram 3 

### ISSUE THREAD

**Issue by peileppe** [n33kos/PhPyChing#4]
following https://en.wikibooks.org/wiki/I_Ching/The_64_Hexagrams

the value for hexagram 3 is "010001" not "100010" in PhPyChing.py

if hexvalue == "100010":
		return "(Chun) Difficulty at the Beginning - 3"

from hexagram 3 - there is a shift of 1
that means when interpret_hexagram(hexvalue) returns an hexagram it is off by 1 
e.g: interpret_hexagram(111011) will return "(Hsiao Ch'u) The Taming Power of the Small - 9"
but it should be 10

**Comment by n33kos** [comment]
@peileppe Thank you so much for noticing the flaw in the repository! When I looked into correcting the issue, I decided to abandon support for this library in lieu of the API version I've been using. Hardcoding the text was a quick solution to get this up and running initially, but is too error prone to continue.

Please head over to https://github.com/n33kos/iChingAPI for a php api version of this service which uses a sqlite API to store the data instead of hardcoding the text which makes mistakes much easier to correct.
